### ISSUE TITLE
examples does not work

### ISSUE THREAD

**Issue by linhnv2801** [rajasimon/beatserver#20]
![image](https://user-images.githubusercontent.com/22856689/205496433-02be57a4-a968-4234-8e8f-440dfa1edf0a.png)
![image](https://user-images.githubusercontent.com/22856689/205496537-5a3da3a7-bf00-48fd-a50f-6c7e3bfe1695.png)

When I clone this project and run it as follow, but it has problem as picture, please help me to run it.

**Comment by rajasimon** [comment]
Instead of `channels` you have to place `daphne` ( I guess alias `runserver` moved to `daphne` from `channels`). 

I have also updated the codebase. You just do `git pull` or see the changes here [90096da](https://github.com/rajasimon/beatserver/commit/90096da32739a912baf03f3e1f433a61a88c2a4a)  and 64c94c7 

let me know if you need further assistance.

**Comment by linhnv2801** [comment]
It's work! 
Thank you very much!
